# ワークフローの名前
name: 'GraphQL: Check for Breaking Changes'

# 実行されるタイミングを定義
on:
  pull_request:
    branches: [ main ]
    # スキーマファイルが変更された場合のみ実行
    paths:
      - '**/schema.graphql'

# 実行されるジョブを定義
jobs:
  # "check-schema"という名前のジョブ
  check-schema:
    name: Check for Breaking Changes
    # どのOSで実行するか
    runs-on: ubuntu-latest
    # 実行する具体的な手順
    steps:
      # 1. リポジトリのコードをコピーする
      - uses: actions/checkout@v4

      # 2. GraphQL Inspectorを実行する
      # 公開されている便利なアクション(ツール)を利用
      - uses: graphql-hive/graphql-inspector@v4
        # Inspectorに渡す設定
        with:
          # 比較対象:
          # `main`ブランチにある`schema.graphql`ファイル(変更前)と
          # このプルリクエスト内の`schema.graphql`ファイル(変更後)を比べる
          schema: main:schema.graphql

          # 破壊的な変更が見つかったら、ワークフローを失敗させる
          fail-on-breaking: true

          # 変更点をプルリクエストのレビュー画面にコメントとして自動で書き込む
          annotations: true

          # GitHub APIと連携するためのトークン(必須)
          github-token: ${{ secrets.GITHUB_TOKEN }}